### PR TITLE
Julia 0.7

### PR DESCRIPTION
**Pull request by femtotrader**

### CODE REVIEW

**Comment by femtotrader** [comment]
@iblis17 2 tests are still failling.
Any idea?

**Comment by iblislin** [comment]
I guess the new optimizer in 0.7 is conservative.

**Comment by iblislin** [comment]
there are still some depwarns, seems femtocleaner missed the case of `range`?
```julia
   Testing TimeFrames
 Resolving package versions...
Test Summary:            | Pass  Total
low level (period frame) |   16     16
┌ Warning: `range(start, step, length)` is deprecated, use `range(start, step=step, length=length)` instead.
│   caller = range(::DateTime, ::DatePeriodFrame{Day}, ::Int64) at TimeFrames.jl:270
└ @ TimeFrames ~/.julia/dev/TimeFrames/src/TimeFrames.jl:270
┌ Warning: `range(start, step, length)` is deprecated, use `range(start, step=step, length=length)` instead.
│   caller = range(::DatePeriodFrame{Day}, ::DateTime, ::Int64) at TimeFrames.jl:274
└ @ TimeFrames ~/.julia/dev/TimeFrames/src/TimeFrames.jl:274
┌ Warning: InexactError now supports arguments, use `InexactError(funcname::Symbol, ::Type, value)` instead.
│   caller = ip:0x0
└ @ Core :-1
Test Summary: | Pass  Total
high level    |  163    163
   Testing TimeFrames tests passed
```

**Comment by femtotrader** [comment]
Thanks @iblis17 
I will tackle depwarns in an other PR

**Pull request merged**
